os:
- Visual Studio 2017

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - vcpkg install gtest tl-expected
  - vcpkg integrate install
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake
  - cmake --build .
  - ctest

cache: c:\Tools\vcpkg\installed\
