image:
 - Visual Studio 2017
 - Visual Studio 2019

platform:
  - x64

configuration:
  - Debug
  - Release

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - vcpkg install tl-expected catch2 nlohmann-json
  - vcpkg integrate install
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake
  - cmake --build .
  - ctest

cache: c:\Tools\vcpkg\installed\

matrix:
  fast_finish: true

on_failure:
 - type Testing\Temporary\LastTest.log
