image:
 - Visual Studio 2017
 - Visual Studio 2019

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  matrix:
    - SHARED_LIB: OFF

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - vcpkg install tl-expected catch2 nlohmann-json fmt --triplet x64-windows
  - vcpkg integrate install
  - cd %APPVEYOR_BUILD_FOLDER%

before_build:
 - git submodule init
 - git submodule update
 - mkdir build
 - cmake
  -B build
  -A x64
  -DSkyr_WARNINGS_AS_ERRORS=OFF
  -DSkyr_BUILD_TESTS=ON
  -DSkyr_BUILD_WPT_TESTS=ON
  -DSkyr_BUILD_DOCS=OFF
  -DSkyr_BUILD_EXAMPLES=OFF
  -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake
  -DBUILD_SHARED_LIBS=%SHARED_LIB%
  .

build_script:
  - cmake --build build

test_script:
 - cd build
 - ctest
 - cd ..


cache: c:\Tools\vcpkg\installed\

matrix:
  fast_finish: true

on_failure:
 - type Testing\Temporary\LastTest.log
