// Copyright 2018-19 Glyn Matthews.
// Copyright 2006-2016 Nemanja Trifunovic
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)


/*
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef SKYR_UNICODE_IMPL_INC
#define SKYR_UNICODE_IMPL_INC

#include <algorithm>
#include <skyr/unicode/unicode.hpp>

namespace skyr {
namespace unicode {
namespace constants {
// Unicode constants
// Leading (high) surrogates: 0xd800 - 0xdbff
// Trailing (low) surrogates: 0xdc00 - 0xdfff
namespace surrogates {
constexpr char16_t lead_min = 0xd800u;
constexpr char16_t lead_max = 0xdbffu;
constexpr char16_t trail_min = 0xdc00u;
constexpr char16_t trail_max = 0xdfffu;
constexpr char16_t lead_offset = lead_min - (0x10000u >> 10u);
constexpr char32_t offset = 0x10000u - (lead_min << 10) - trail_min;
}  // namespace surrogates

namespace code_points {
// Maximum valid value for a Unicode code point
constexpr char32_t max = 0x0010ffffu;
}  // namespace code_points
}  // namespace constants

template <typename OctetType>
constexpr uint8_t mask8(OctetType octet) {
  return static_cast<uint8_t>(0xff & octet);
}

template <typename U16Type>
constexpr char16_t mask16(U16Type octet) {
  return static_cast<char16_t>(0xffff & octet);
}

template <typename OctetType>
constexpr bool is_trail(OctetType octet) {
  return ((mask8(octet) >> 6) == 0x2);
}

constexpr bool is_lead_surrogate(char16_t code_point) {
  return
  (code_point >= constants::surrogates::lead_min) &&
  (code_point <= constants::surrogates::lead_max);
}

constexpr bool is_trail_surrogate(char16_t code_point) {
  return
  (code_point >= constants::surrogates::trail_min) &&
  (code_point <= constants::surrogates::trail_max);
}

constexpr bool is_surrogate(char16_t code_point) {
  return
  (code_point >= constants::surrogates::lead_min) &&
  (code_point <= constants::surrogates::trail_max);
}

constexpr bool is_valid_code_point(char32_t code_point) {
  return
  (code_point <= constants::code_points::max) &&
  !is_surrogate(static_cast<char16_t>(code_point));
}

template <typename OctetIterator>
constexpr std::size_t sequence_length(
    OctetIterator lead_it) {
  auto lead = mask8(*lead_it);
  if (lead < 0x80) {
    return 1;
  } else if ((lead >> 5) == 0x6) {
    return 2;
  } else if ((lead >> 4) == 0xe) {
    return 3;
  } else if ((lead >> 3) == 0x1e) {
    return 4;
  }
  return 0;
}

constexpr bool is_overlong_sequence(
    char32_t code_point,
    std::size_t length) {
  bool result = false;
  result &= (code_point < 0x80) && (length != 1);
  result &= (code_point < 0x800) && (length != 2);
  result &= (code_point < 0x10000) && (length != 3);
  return result;
}

template <typename OctetIterator>
class sequence_state {

 public:

  sequence_state(
      char32_t code_point,
      OctetIterator it,
      OctetIterator last)
      : code_point(code_point)
      , it(it)
      , last(last) {}

  char32_t code_point;
  OctetIterator it;
  OctetIterator last;
};

template <typename OctetIterator>
tl::expected<sequence_state<OctetIterator>, unicode::unicode_errc>
increment(sequence_state<OctetIterator> state) {
  ++state.it;

  if (state.it == state.last) {
    return tl::make_unexpected(unicode::unicode_errc::overflow);
  }

  if (!is_trail(*state.it)) {
    return tl::make_unexpected(unicode::unicode_errc::illegal_byte_sequence);
  }

  return state;
}

template <typename OctetIterator>
tl::expected<sequence_state<OctetIterator>, unicode::unicode_errc>
from_sequence_1(
    OctetIterator it,
    OctetIterator last) {
  if (it == last) {
    return tl::make_unexpected(unicode::unicode_errc::overflow);
  }
  return sequence_state<OctetIterator>{mask8(*it), it, last};
}

template <typename OctetIterator>
tl::expected<sequence_state<OctetIterator>, unicode::unicode_errc>
from_sequence_2(OctetIterator first, OctetIterator last) {
  using result_type = tl::expected<sequence_state<OctetIterator>, unicode::unicode_errc>;

  return
      from_sequence_1(first, last)
          .and_then([] (auto state) {
            return increment(state);
          })
          .and_then([] (auto state) -> result_type {
            return sequence_state<OctetIterator>{
                ((state.code_point << 6) & 0x7ff) + (*state.it & 0x3f),
                state.it,
                state.last};
          });
}

template <typename OctetIterator>
tl::expected<sequence_state<OctetIterator>, unicode::unicode_errc>
from_sequence_3(OctetIterator first, OctetIterator last) {
  using result_type = tl::expected<sequence_state<OctetIterator>, unicode::unicode_errc>;

  return
      from_sequence_1(first, last)
          .and_then([] (auto state) -> result_type {
            return increment(state);
          })
          .and_then([] (auto state) -> result_type {
            return sequence_state<OctetIterator>{
                ((state.code_point << 12) & 0xffff) +
                ((mask8(*state.it) << 6) & 0xfff),
                state.it,
                state.last};
          })
          .and_then([] (auto state) -> result_type {
            return increment(state);
          })
          .and_then([] (auto state) -> result_type {
            return sequence_state<OctetIterator>{
                state.code_point + (*state.it & 0x3f),
                state.it,
                state.last};
          });
}

template <typename OctetIterator>
tl::expected<sequence_state<OctetIterator>, unicode::unicode_errc>
from_sequence_4(OctetIterator first, OctetIterator last) {
  using result_type = tl::expected<sequence_state<OctetIterator>, unicode::unicode_errc>;

  return
      from_sequence_1(first, last)
          .and_then([] (auto state) -> result_type {
            return increment(state);
          })
          .and_then([] (auto state) -> result_type {
            return sequence_state<OctetIterator>{
                ((state.code_point << 18) & 0x1fffff) +
                ((mask8(*state.it) << 12) & 0x3ffff),
                state.it,
                state.last};
          })
          .and_then([] (auto state) -> result_type {
            return increment(state);
          })
          .and_then([] (auto state) -> result_type {
            return sequence_state<OctetIterator>{
                state.code_point + ((mask8(*state.it) << 6) & 0xfff),
                state.it,
                state.last};
          })
          .and_then([] (auto state) -> result_type {
            return increment(state);
          })
          .and_then([] (auto state) -> result_type {
            return sequence_state<OctetIterator>{
                state.code_point + (*state.it & 0x3f),
                state.it,
                state.last};
          })
          ;
}

template <typename OctetIterator>
tl::expected<sequence_state<OctetIterator>, unicode::unicode_errc> find_code_point(
    OctetIterator it,
    OctetIterator last) {
  const auto length = sequence_length(it);
  return
      (length == 1) ? from_sequence_1(it, last) :
      (length == 2) ? from_sequence_2(it, last) :
      (length == 3) ? from_sequence_3(it, last) :
      (length == 4) ? from_sequence_4(it, last) :
      tl::make_unexpected(unicode::unicode_errc::overflow)
  ;
}

template <typename OctetIterator>
tl::expected<sequence_state<OctetIterator>, unicode::unicode_errc> validate_next(
    OctetIterator it,
    OctetIterator last) {
  using result_type = tl::expected<sequence_state<OctetIterator>, unicode::unicode_errc>;

  if (it == last) {
    return tl::make_unexpected(unicode::unicode_errc::overflow);
  }

  return find_code_point(it, last)
  .and_then([] (auto state) -> result_type {
    if (!is_valid_code_point(state.code_point)) {
      return tl::make_unexpected(unicode::unicode_errc::invalid_code_point);
    } else if (is_overlong_sequence(state.code_point, sequence_length(state.it))) {
      return tl::make_unexpected(unicode::unicode_errc::illegal_byte_sequence);
    }

    ++state.it;
    return state;
  });
}

template <typename OctetIterator>
OctetIterator find_invalid(
    OctetIterator first,
    OctetIterator last) {
  using result_type = tl::expected<sequence_state<OctetIterator>, unicode::unicode_errc>;

  auto it = first;
  while (it != last) {
    auto result = validate_next(it, last)
        .and_then([] (auto state) -> result_type {
          return increment(state);
        }
        .and_then([&it] (auto state) -> result_type {
          it = state.it;
          return state;
        }));
    if (!result) {
      break;
    }
  }
  return it;
}

template <typename OctetIterator>
constexpr bool is_valid(
    OctetIterator first,
    OctetIterator last) {
  return find_invalid(first, last) == last;
}

template <typename OctetIterator>
tl::expected<OctetIterator, unicode::unicode_errc> append(
    char32_t code_point,
    OctetIterator result) {
  if (!is_valid_code_point(code_point)) {
    return tl::make_unexpected(unicode::unicode_errc::invalid_code_point);
  }

  if (code_point < 0x80) { // one octet
    *(result++) = static_cast<uint8_t>(code_point);
  }
  else if (code_point < 0x800) {  // two octets
    *(result++) = static_cast<uint8_t>((code_point >> 6) | 0xc0);
    *(result++) = static_cast<uint8_t>((code_point & 0x3f) | 0x80);
  } else if (code_point < 0x10000) {  // three octets
    *(result++) = static_cast<uint8_t>((code_point >> 12) | 0xe0);
    *(result++) = static_cast<uint8_t>(((code_point >> 6) & 0x3f) | 0x80);
    *(result++) = static_cast<uint8_t>((code_point & 0x3f) | 0x80);
  } else {  // four octets
    *(result++) = static_cast<uint8_t>((code_point >> 18) | 0xf0);
    *(result++) = static_cast<uint8_t>(((code_point >> 12) & 0x3f) | 0x80);
    *(result++) = static_cast<uint8_t>(((code_point >> 6) & 0x3f) | 0x80);
    *(result++) = static_cast<uint8_t>((code_point & 0x3f) | 0x80);
  }
  return result;
}

template <typename OctetIterator>
tl::expected<sequence_state<OctetIterator>, unicode::unicode_errc> next(
    OctetIterator it,
    OctetIterator last) {
  return validate_next(it, last);
}

template <typename OctetIterator>
tl::expected<sequence_state<OctetIterator>, unicode::unicode_errc> peek_next(
    OctetIterator it,
    OctetIterator last) {
  return next(it, last)
  .and_then([&it] (auto state) {
    state.it = it;
    return state;
  });
}

template <typename OctetIterator>
tl::expected<sequence_state<OctetIterator>, unicode::unicode_errc> prior(
    OctetIterator it,
    OctetIterator first) {
  if (it == first) {
    return tl::make_unexpected(unicode::unicode_errc::overflow);
  }

  auto last = it;
  // Go back until we hit either a lead octet or start
  --it;
  while (is_trail(*it)) {
    if (it == first) {
      return tl::make_unexpected(unicode::unicode_errc::invalid_code_point);
    }
    --it;
  }
  return peek_next(it, last);
}

template <typename OctetIterator>
tl::expected<void, unicode::unicode_errc> advance(
    OctetIterator& it,
    std::size_t n,
    OctetIterator end) {
  while (n != 0) {
    auto state = next(it, end)
        .and_then([&it, &n] (auto state) {
          it = state.it;
          --n;
        });
  }
}

template <typename OctetIterator>
tl::expected<std::size_t, unicode::unicode_errc> distance(
    OctetIterator first,
    OctetIterator last) {
  std::size_t distance = 0;
  auto it = first;
  while (it != last) {
    auto state = next(it, last)
        .and_then([&distance, &it] (auto state) {
          ++distance;
          it = state.it;
        });
    if (!state) {
      return tl::make_unexpected(state.error());
    }
  }
  return distance;
}

template <typename U16BitIterator, typename OctetIterator>
tl::expected<OctetIterator, unicode::unicode_errc> utf16to8(
    U16BitIterator first,
    U16BitIterator last,
    OctetIterator result) {
  auto it = first;
  while (it != last) {
    auto code_point = static_cast<std::uint32_t>(mask16(*it));
    ++it;

    // Take care of surrogate pairs first
    if (is_lead_surrogate(code_point)) {
      if (it != last) {
        auto trail_surrogate = mask16(*it);
        ++it;
        if (is_trail_surrogate(trail_surrogate)) {
          code_point = (code_point << 10) + trail_surrogate + constants::surrogates::offset;
        }
        else {
          return tl::make_unexpected(unicode::unicode_errc::invalid_code_point);
        }
      } else {
        return tl::make_unexpected(unicode::unicode_errc::invalid_code_point);
      }
    }
    else if (is_trail_surrogate(code_point)) {
      return tl::make_unexpected(unicode::unicode_errc::invalid_code_point);
    }

    auto result_it = append(code_point, result);
    if (!result_it) {
      return tl::make_unexpected(std::move(result_it.error()));
    }
  }
  return result;
}

template <typename U16BitIterator, typename OctetIterator>
tl::expected<U16BitIterator, unicode::unicode_errc> utf8to16(
    OctetIterator first,
    OctetIterator last,
    U16BitIterator result) {
  auto it = first;
  while (it != last) {
    auto state = next(it, last)
        .and_then([&it, &result] (auto state) -> tl::expected<void, unicode::unicode_errc> {
          it = state.it;

          if (state.code_point > 0xffff) {  // make a surrogate pair
            *result++ =
                static_cast<char16_t>((state.code_point >> 10) +
                    constants::surrogates::lead_offset);
            *result++ =
                static_cast<char16_t>((state.code_point & 0x3ff) +
                    constants::surrogates::trail_min);
          } else {
            *result++ = static_cast<char16_t>(state.code_point);
          }

          return {};
        });
    if (!state) {
      return tl::make_unexpected(std::move(state.error()));
    }
  }
  return result;
}

template <typename OctetIterator, typename U32BitIterator>
tl::expected<OctetIterator, unicode::unicode_errc> utf32to8(
    U32BitIterator first,
    U32BitIterator last,
    OctetIterator result) {
  auto it = first;
  while (it != last) {
    auto result_it = append(*it, result)
        .and_then([&result, &it] (auto octet_it) -> tl::expected<void, unicode::unicode_errc> {
          result = octet_it;
          ++it;
          return {};
        });
    if (!result_it) {
      return tl::make_unexpected(std::move(result_it.error()));
    }
  }
  return result;
}

template <typename OctetIterator, typename U32BitIterator>
tl::expected<U32BitIterator, unicode::unicode_errc> utf8to32(
    OctetIterator first,
    OctetIterator last,
    U32BitIterator result) {
  auto it = first;
  while (it != last) {
    auto state = next(it, last)
        .and_then([&it, &result] (auto state) -> tl::expected<void, unicode::unicode_errc> {
          it = state.it;
          (*result++) = state.code_point;
          return {};
        });
    if (!state) {
      return tl::make_unexpected(std::move(state.error()));
    }
  }
  return result;
}
}  // namespace unicode
}  // namespace skyr

#endif  // SKYR_UNICODE_IMPL_INC
